name: Deploy lambda function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: | 
          cd function
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Zip ALL
        run: |
          cd function
          zip -r ../${{ github.sha }}.zip .
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip 
          
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Dwonload build
        uses: actions/download-artifact@v4
        with:
          name: zipped-bundle
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
          aws-region: us-east-1
      - name: Upload to S3 bucket
        run: aws s3 cp ${{ github.sha }}.zip s3://github-artifacts-bucket/${{ github.sha }}.zip
      
      
          
